version: '3'

services:
  streamlit-app:
    build: .
    container_name: my-streamlit-app
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    environment:
      - TZ=Europe/Moscow
      - MATTERMOST_URL=${MATTERMOST_URL:-}
      - PRODUCT_NAME=${PRODUCT_NAME:-Mattermost}
      - MATTERMOST_PERSONAL_TOKEN=${MATTERMOST_PERSONAL_TOKEN:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
