version: '3'

services:
  streamlit-app:
    # Используем образ из GitHub Container Registry
    image: ghcr.io/malinborn/mattermost-pulse:latest
    container_name: my-streamlit-app
    restart: always
    ports:
      - "127.0.0.1:8501:8501"
    # В продакшене обычно не маунтят код локально, но можно оставить env файлы или volume для данных
    environment:
      - TZ=Europe/Moscow
      - MATTERMOST_URL=${MATTERMOST_URL:-}
      - PRODUCT_NAME=${PRODUCT_NAME:-Mattermost}
      - MATTERMOST_PERSONAL_TOKEN=${MATTERMOST_PERSONAL_TOKEN:-}